# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='your country', max_length=120)),
                ('state', models.CharField(default='your state', max_length=120)),
                ('cityname', models.CharField(default='your city', max_length=120)),
                ('tour_theme', models.CharField(choices=[('art', 'Art'), ('activity', 'Activity'), ('historic', 'Historic'), ('generic', 'General')], default='generic', max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('tour_intensity', models.CharField(choices=[('sandals', 'Sandals'), ('regular shoes', 'Regular shoes'), ('gym shoes', 'Gym Shoes'), ('hiking shoes', 'Hiking shoes')], default='sandals', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images', width_field='width_field')),
                ('content', models.TextField()),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('slug', models.CharField(default='', max_length=150, unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tour_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('about_you', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
